# Generated by Django 2.1.7 on 2019-03-24 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=100)),
                ('major', models.CharField(max_length=200)),
                ('bio', models.TextField(blank=True, max_length=600)),
                ('skills', models.CharField(blank=True, max_length=100)),
                ('courses', models.CharField(blank=True, max_length=200)),
                ('organizations', models.CharField(blank=True, max_length=200)),
                ('interests', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(default='default-avatar.jpg', upload_to='profile_pics')),
            ],
        ),
    ]
