# Generated by Django 2.2 on 2019-04-14 16:11

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('user_id', models.CharField(max_length=10)),
                ('endorsements', jsonfield.fields.JSONField(blank=True, verbose_name=models.CharField(max_length=10))),
                ('endorse', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='skills',
            field=jsonfield.fields.JSONField(blank=True, verbose_name=models.CharField(max_length=20)),
        ),
    ]
