# Generated by Django 2.1.5 on 2019-04-07 19:57

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_profile_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='json',
            field=jsonfield.fields.JSONField(default=''),
            preserve_default=False,
        ),
    ]
