# Generated by Django 2.2 on 2019-04-22 19:46

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190421_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('endorsements', jsonfield.fields.JSONField(blank=True, verbose_name=models.CharField(default='', max_length=10))),
                ('endorse', models.IntegerField(default=0)),
                ('user_id', models.CharField(max_length=10)),
            ],
        ),
    ]
