# Generated by Django 2.1.5 on 2019-02-24 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_prof'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prof',
            name='user',
        ),
        migrations.DeleteModel(
            name='Prof',
        ),
    ]
