# Generated by Django 2.1.5 on 2019-04-05 14:21

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('app', '0003_friend_current_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='year',
            field=models.CharField(choices=[('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('Graduate Student', 'Graduate Student'), ('Faculty', 'Faculty'), ('Other', 'Other')], max_length=16),
        ),
    ]
