# Generated by Django 2.1.7 on 2019-04-08 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_profile_tags'),
        ('app', '0003_friend_current_user'),
    ]

    operations = [
    ]
