# Generated by Django 2.2 on 2019-04-14 18:51

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190414_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='endorsements',
            field=jsonfield.fields.JSONField(blank=True, verbose_name=models.CharField(default='', max_length=10)),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='skill',
            name='user_id',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
