# Generated by Django 2.2 on 2019-04-22 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='pk_id',
            field=models.IntegerField(default=0),
        ),
    ]
