# Generated by Django 2.2 on 2019-04-22 23:14

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190422_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('endorsements', jsonfield.fields.JSONField(blank=True, verbose_name=models.CharField(default='', max_length=10))),
                ('endorse', models.IntegerField(default=0)),
                ('user_id', models.CharField(max_length=10)),
                ('pk_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='endorse',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='endorsements',
        ),
    ]
