# Generated by Django 2.1.5 on 2019-04-05 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190405_1021'),
        ('app', '0004_auto_20190405_1557'),
    ]

    operations = [
    ]
