# Generated by Django 2.1.5 on 2019-04-08 04:14

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190407_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='endorsements',
            field=jsonfield.fields.JSONField(blank=True, verbose_name=models.CharField(max_length=10)),
        ),
    ]
