# Generated by Django 2.1.5 on 2019-02-24 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default-avatar.jpg', upload_to='profile_pics'),
        ),
    ]
