# Generated by Django 2.2 on 2019-04-08 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190408_0014'),
        ('app', '0003_friend_current_user'),
    ]

    operations = [
    ]
