# Generated by Django 2.2 on 2019-04-08 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190407_2252'),
        ('app', '0005_auto_20190408_0014'),
    ]

    operations = [
    ]
