# Generated by Django 2.1.5 on 2019-02-25 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190224_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_id',
            field=models.CharField(default='', max_length=8),
            preserve_default=False,
        ),
    ]
