# Generated by Django 2.1.5 on 2019-04-08 05:09

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190408_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='endorse',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='endorsements',
            field=jsonfield.fields.JSONField(blank=True, verbose_name=models.CharField(max_length=10)),
        ),
    ]
