# Generated by Django 2.2 on 2019-04-15 03:11

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20190414_2306'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.AddField(
            model_name='profile',
            name='endorse',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='endorsements',
            field=jsonfield.fields.JSONField(blank=True, verbose_name=models.CharField(default='', max_length=10)),
        ),
    ]
